### ISSUE TITLE
Format date correctly on See the Fishway sidebar

### ISSUE THREAD

**Issue by fungjj92** [azavea/pwd-fishway#71]
## Overview

The sidebar / See the Fishway was mostly implemented in #70 . The video date still requires formatting as 'MM DD' but was deferred due to difficulty with moment.js and Datejs.

Current:
<img width="611" alt="Screen Shot 2019-05-02 at 11 13 08 AM" src="https://user-images.githubusercontent.com/10568752/57786393-62563400-7701-11e9-8608-bdad4c5da638.png">

Desired:
<img width="1158" alt="Screen Shot 2019-05-14 at 2 54 56 PM" src="https://user-images.githubusercontent.com/10568752/57786363-52d6eb00-7701-11e9-8430-7bc8660e9f0d.png">

**Comment by maurizi** [comment]
I've used [`Luxon`](https://moment.github.io/luxon/) in Treetective for simple date formatting and found it to be effective. Pros: hard to mess up API, uses native timezone information from the browser instead of needing to continually update a tz database. Cons: not as fully featured, requires modern browsers.

Alternatively, I think it would be fine to just manually format these dates to our desired format in our `constants.js` file.

**Comment by fungjj92** [comment]
D'oh, reformatting in the constants is a great idea. Let's go with that. Better yet, adding a new field, so we don't lose the timestamp data should we want to reformat as per client.
